### ISSUE TITLE
<idea> Publicly avalible builds? [#2]

### ISSUE THREAD

**Issue by electron271** [RTSProductions/RTSEngine#2]
Add releases for Windows, MacOS and Linux?

**Comment by RTSProductions** [comment]
wdym?

**Comment by electron271** [comment]
like precompiled versions

**Comment by RTSProductions** [comment]
precompiled versions?

**Comment by RTSProductions** [comment]
well that would mean I would have to make an editor and that's pretty complicated, but if I get really advanced at this then maybe.
